# Generated by Django 3.2.7 on 2021-10-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
